---
- hosts: all
  vars:
      tmux_config: "fancy"
      # I want to have tmux spawned always when new terminal window is opened
      # on the desktop
      use_tmux_always: true
  roles:
      - { role: linux_desktop, ansible_python_interpreter: /usr/bin/python3 }
      - { role: vagrant, ansible_python_interpreter: /usr/bin/python3 }
      - { role: libvirt, ansible_python_interpreter: /usr/bin/python3 }
      - { role: base_configs }
      - { role: desktop_configs }
      - { role: i3wm, ansible_python_interpreter: /usr/bin/python3 }
      - { role: mail_cli_tools, ansible_python_interpreter: /usr/bin/python3 }
      - { role: ansible }
      - { role: podman }
      - { role: rh_dev, when: ansible_distribution == 'Fedora' }
      - { role: fzf, ansible_python_interpreter: /usr/bin/python3 }
