---
- hosts: all
  vars:
      tmux_config: "fancy"
  roles:
      - { role: linux_desktop, ansible_python_interpreter: /usr/bin/python3 }
      - { role: vagrant, ansible_python_interpreter: /usr/bin/python3 }
      - { role: libvirt, ansible_python_interpreter: /usr/bin/python3 }
      - { role: base_configs }
      - { role: desktop_configs }
      - { role: i3wm, ansible_python_interpreter: /usr/bin/python3 }
      - { role: ansible }
      - { role: podman }
      - { role: rh_dev, when: ansible_distribution == 'Fedora' }
      - { role: fzf, ansible_python_interpreter: /usr/bin/python3 }
