---
- hosts: all
  vars:
      tmux_config: "fancy"
      desktop_type: "i3"
  roles:
      - { role: linux_desktop, ansible_python_interpreter: /usr/bin/python3 }
      - { role: vagrant, ansible_python_interpreter: /usr/bin/python3 }
      - { role: libvirt, ansible_python_interpreter: /usr/bin/python3 }
      - { role: base_configs }
      - { role: desktop_configs }
      - { role: linux_configs }
      - { role: ansible }
      - { role: podman }
      - { role: rh_dev }
      - { role: fzf, ansible_python_interpreter: /usr/bin/python3 }
